### ISSUE TITLE
Raise error if search() fails

### ISSUE THREAD

**Issue by mhinz** [AndrewRadev/vimrunner#47]
Hi,

I'm working quite a lot on vim-elixir at the moment. It uses the following code:

```ruby
  def syntax(content, pattern)
    with_file content
    # move cursor the pattern
    @vim.search pattern
    # get a list of the syntax element
    @vim.echo <<~EOF
    map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
    EOF
  end
```

This works good enough, if the pattern actually exists. Otherwise the cursor won't move and it reports the syntax groups from column 0. But if the pattern isn't found, it should return `[]` instead.

What's the best way to achieve this? I guess this needs to be fixed so that `search()` does a `remote_send()` that catches errors?

**Comment by AndrewRadev** [comment]
Hmm. The `search` method types in `/<pattern>`, which is why it doesn't capture errors. Invoking it as a command, however, does the trick:

```
irb(main):009:0> $vim.command(':/existing')
=> ""
irb(main):010:0> $vim.command(':/nonexisting')
Vimrunner::InvalidCommandError: Vim:E486: Pattern not found: nonexisting
	from /home/andrew/.gem/ruby/2.3.1/gems/vimrunner-0.3.3/lib/vimrunner/client.rb:193:in `block in command'
	from /home/andrew/.gem/ruby/2.3.1/gems/vimrunner-0.3.3/lib/vimrunner/client.rb:192:in `tap'
	from /home/andrew/.gem/ruby/2.3.1/gems/vimrunner-0.3.3/lib/vimrunner/client.rb:192:in `command'
	from (irb):10
	from /home/andrew/.gem/ruby/2.3.1/gems/vimrunner-0.3.3/bin/vimrunner:10:in `<top (required)>'
	from /home/andrew/.gem/ruby/2.3.1/bin/vimrunner:23:in `load'
	from /home/andrew/.gem/ruby/2.3.1/bin/vimrunner:23:in `<main>'
irb(main):011:0> 
```

Alternatively, you could call the function `search()`:

``` ruby
irb(main):015:0> $vim.echo("search('existing')")
=> "3"
irb(main):016:0> $vim.echo("search('nonexisting')")
=> "0"
irb(main):017:0> 
```

Admittedly, in this case you'd need some escaping of quotes, but I think it wouldn't be that hard to encapsulate it.

Would these ways of doing searches work for your use cases? Or would you like to talk more about the general question of "how *should* the built-in search method work". I didn't really have much of a design goal in mind when I added it the way I did, I guess, it's just a thin wrapper around `type`: https://github.com/AndrewRadev/vimrunner/blob/435c14ed0aceab9aff199d925d6511ab0c9839ed/lib/vimrunner/client.rb#L94-L95

**Comment by mhinz** [comment]
Oh, now that was easy. This totally works for me:

```ruby
  def syntax(content, pattern)
    with_file content
    @vim.search pattern
    begin
      @vim.command "/#{pattern}"
    rescue Vimrunner::InvalidCommandError
      return []
    end
    @vim.echo <<~EOF
    map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
    EOF
  end
```

Thank you for your quick response!

**Comment by mhinz** [comment]
Oops, I was a bit hasty. `:/` only jumps to lines, not exact positions.

**Comment by AndrewRadev** [comment]
Yeah, I think I get what's going on. I guess that, technically, `:/foo` is a *range*. Typing `d/foo<cr>` is going to delete to the next "foo", for instance. I have no idea what the syntax for this would be in combination with a command, but this is probably how it parses to Vim at least.

So, yeah, that doesn't really work as a normal "search", which is why it doesn't add anything to the search history. How curious :).

Anyway, what about the `search()` function?

**Comment by mhinz** [comment]
> So, yeah, that doesn't really work as a normal "search", which is why it doesn't add anything to the search history.

Except it does!

```vim
:/foo
:echo @/
foo
:/bar
:echo @/
bar
```

That's why I assumed that `@vim.normal 'n'` would work afterwards.

> Anyway, what about the `search()` function?

I'm going to try this now. :]

**Comment by mhinz** [comment]
Okay, it looks like this works for vim-elixir's test suite (and even finds 5 useless tests that only worked by accident because the cursor didn't move when the search term wasn't found):

```vim
  def syntax(content, pattern)
    with_file content
    if @vim.echo("search(#{pattern.inspect})") == '0'
      return []
    end
    @vim.echo <<~EOF
    map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
    EOF
  end
```

Thank you!

(BTW, I hope you don't mind that I'm not very active in neomake.. too much on my own plate. But I proudly sport its badge in my GitHub profile. :-))

**Comment by AndrewRadev** [comment]
> Except it does!

Okay, I have to admit, I have no explanation, then :D. Might just be in the category of "undefined behaviour".

> Okay, it looks like this works for vim-elixir's test suite

Cool, glad I could help :).
